# Generated by Django 4.1.3 on 2022-11-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('source_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_description', models.CharField(max_length=50, null=True)),
                ('transaction_value', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.source')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='source_users',
            field=models.ManyToManyField(to='book.user'),
        ),
    ]
