# Generated by Django 4.1.3 on 2022-11-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_users',
            field=models.ManyToManyField(blank=True, related_name='users', to='book.user'),
        ),
    ]
