# Generated by Django 4.1.3 on 2022-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_source_source_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_users',
            field=models.ManyToManyField(blank=True, related_name='sources', to='book.user'),
        ),
    ]
