# Generated by Django 4.1.3 on 2022-12-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_source_source_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.user'),
            preserve_default=False,
        ),
    ]
